export const adminSidebarMenu = [
  {
    type: "link",
    label: "Dashboard",
    path: "/admin/food",
    icon: "LayoutDashboard",
    permissionKey: "dashboard",
  },
  {
    type: "link",
    label: "Point of Sale",
    path: "/admin/food/point-of-sale",
    icon: "CreditCard",
    permissionKey: "pos",
  },
  {
    type: "link",
    label: "Real Time Status",
    path: "/admin/food/status-monitor",
    icon: "MapPin",
    permissionKey: "orders",
  },
  {
    type: "section",
    label: "FOOD MANAGEMENT",
    permissionKey: "foods",
    items: [
      {
        type: "link",
        label: "Food Approval",
        path: "/admin/food/food-approval",
        icon: "CheckCircle2",
        permissionKey: "foods",
      },
      {
        type: "expandable",
        label: "Foods",
        icon: "Utensils",
        permissionKey: "foods",
        subItems: [
          { label: "Restaurant Foods List", path: "/admin/food/foods" },
          { label: "Restaurant Addons List", path: "/admin/food/addons" },
        ],
      },
      {
        type: "expandable",
        label: "Categories",
        icon: "FolderTree",
        permissionKey: "categories",
        subItems: [{ label: "Category", path: "/admin/food/categories" }],
      },
    ],
  },
  {
    type: "section",
    label: "RESTAURANT MANAGEMENT",
    permissionKey: "restaurants",
    items: [
      {
        type: "link",
        label: "Zone Setup",
        path: "/admin/food/zone-setup",
        icon: "MapPin",
        permissionKey: "zones",
      },
      {
        type: "expandable",
        label: "Restaurants",
        icon: "UtensilsCrossed",
        permissionKey: "restaurants",
        subItems: [
          { label: "Restaurants List", path: "/admin/food/restaurants" },
          { label: "New Joining Request", path: "/admin/food/restaurants/joining-request" },
          { label: "Restaurant Commission", path: "/admin/food/restaurants/commission" },
          { label: "Restaurant Reviews", path: "/admin/food/restaurants/reviews" },
          { label: "Restaurant Complaints", path: "/admin/food/restaurants/complaints" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "ORDER MANAGEMENT",
    permissionKey: "orders",
    items: [
      {
        type: "expandable",
        label: "Orders",
        icon: "FileText",
        permissionKey: "orders",
        subItems: [
          { label: "All", path: "/admin/food/orders/all" },
          { label: "Scheduled", path: "/admin/food/orders/scheduled" },
          { label: "Pending", path: "/admin/food/orders/pending" },
          { label: "Processing", path: "/admin/food/orders/processing" },
          { label: "Food On The Way", path: "/admin/food/orders/food-on-the-way" },
          { label: "Delivered", path: "/admin/food/orders/delivered" },
          { label: "Cancelled", path: "/admin/food/orders/canceled" },
          { label: "Restaurant cancelled", path: "/admin/food/orders/restaurant-cancelled" },
          { label: "Payment Failed", path: "/admin/food/orders/payment-failed" },
          { label: "Refunded", path: "/admin/food/orders/refunded" },
          { label: "Offline Payments", path: "/admin/food/orders/offline-payments" },
        ],
      },
      {
        type: "link",
        label: "Order Detect Delivery",
        path: "/admin/food/order-detect-delivery",
        icon: "Truck",
        permissionKey: "orders",
      },
    ],
  },
  {
    type: "section",
    label: "PROMOTIONS MANAGEMENT",
    permissionKey: "promotions",
    items: [
      {
        type: "link",
        label: "Restaurant Coupons & Offers",
        path: "/admin/food/coupons",
        icon: "Gift",
        permissionKey: "promotions",
      },
    ],
  },
  {
    type: "section",
    label: "REFERRAL & REWARDS",
    permissionKey: "referrals",
    items: [
      { type: "link", label: "Referral Settings", path: "/admin/food/referral-settings", icon: "Gift", permissionKey: "referrals" },
    ],
  },
  {
    type: "section",
    label: "CUSTOMER MANAGEMENT",
    permissionKey: "customers",
    items: [
      {
        type: "link",
        label: "Customers",
        path: "/admin/food/customers",
        icon: "Users",
        permissionKey: "customers",
      },
      {
        type: "link",
        label: "Support Tickets (User & Restaurant)",
        path: "/admin/food/support-tickets",
        icon: "MessageSquare",
        permissionKey: "support",
      },
    ],
  },
  {
    type: "section",
    label: "DELIVERYMAN MANAGEMENT",
    permissionKey: "delivery",
    items: [
      { type: "link", label: "Delivery Cash Limit", path: "/admin/food/delivery-cash-limit", icon: "IndianRupee", permissionKey: "delivery" },
      { type: "link", label: "Delivery & Platform Fee", path: "/admin/food/fee-settings", icon: "DollarSign", permissionKey: "fee_settings" },
      // { type: "link", label: "Mixed Order Eligibility", path: "/admin/food/mixed-order-eligibility", icon: "Settings2" },

      { type: "link", label: "Cash limit settlement", path: "/admin/food/cash-limit-settlement", icon: "Receipt", permissionKey: "delivery" },
      { type: "link", label: "Delivery Withdrawal", path: "/admin/food/delivery-withdrawal", icon: "Wallet", permissionKey: "wallet" },
      { type: "link", label: "Delivery boy Wallet", path: "/admin/food/delivery-boy-wallet", icon: "PiggyBank", permissionKey: "wallet" },
      { type: "link", label: "Delivery Boy Commission", path: "/admin/food/delivery-boy-commission", icon: "DollarSign", permissionKey: "delivery" },
      { type: "link", label: "Delivery Emergency Help", path: "/admin/food/delivery-emergency-help", icon: "Phone", permissionKey: "delivery" },
      { type: "link", label: "Delivery Support Tickets", path: "/admin/food/delivery-support-tickets", icon: "MessageSquare", permissionKey: "support" },
      {
        type: "expandable",
        label: "Deliveryman",
        icon: "Package",
        permissionKey: "delivery",
        subItems: [
          { label: "New Join Request", path: "/admin/food/delivery-partners/join-request" },
          { label: "Deliveryman List", path: "/admin/food/delivery-partners" },
          { label: "Deliveryman Reviews", path: "/admin/food/delivery-partners/reviews" },
          { label: "Bonus", path: "/admin/food/delivery-partners/bonus" },
          { label: "Earning Addon", path: "/admin/food/delivery-partners/earning-addon" },
          { label: "Earning Addon History", path: "/admin/food/delivery-partners/earning-addon-history" },
          { label: "Delivery Earning", path: "/admin/food/delivery-partners/earnings" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "HELP & SUPPORT",
    permissionKey: "support",
    items: [
      { type: "link", label: "User Feedback", path: "/admin/food/contact-messages", icon: "Mail", permissionKey: "support" },
      { type: "link", label: "Safety Emergency Reports", path: "/admin/food/safety-emergency-reports", icon: "AlertTriangle", permissionKey: "support" },
    ],
  },
  {
    type: "section",
    label: "REPORT MANAGEMENT",
    permissionKey: "reports",
    items: [
      { type: "link", label: "Transaction Report", path: "/admin/food/transaction-report", icon: "FileText", permissionKey: "reports" },
      { type: "link", label: "Order Report", path: "/admin/food/order-report/regular", icon: "FileText", permissionKey: "reports" },
      { type: "link", label: "Tax Report", path: "/admin/food/tax-report", icon: "Receipt", permissionKey: "reports" },
      {
        type: "expandable",
        label: "Restaurant Report",
        icon: "FileText",
        permissionKey: "reports",
        subItems: [{ label: "Restaurant Report", path: "/admin/food/restaurant-report" }],
      },
      {
        type: "expandable",
        label: "Customer Report",
        icon: "FileText",
        permissionKey: "reports",
        subItems: [{ label: "Feedback Experience", path: "/admin/food/customer-report/feedback-experience" }],
      },
    ],
  },
  {
    type: "section",
    label: "TRANSACTION MANAGEMENT",
    permissionKey: "wallet",
    items: [
      { type: "link", label: "Restaurant Withdraws", path: "/admin/food/restaurant-withdraws", icon: "CreditCard", permissionKey: "wallet" },
    ],
  },
  {
    type: "section",
    label: "BANNER SETTINGS",
    permissionKey: "cms",
    items: [
      { type: "link", label: "Landing Page Management", path: "/admin/food/hero-banner-management", icon: "Image", permissionKey: "cms" },
    ],
  },

  {
    type: "section",
    label: "SYSTEM SETTINGS",
    permissionKey: "settings",
    items: [
      { type: "link", label: "Broadcast Notification", path: "/admin/food/broadcast-notification", icon: "Bell", permissionKey: "settings" },
    ],
  },
  {
    type: "section",
    label: "PAGES & SOCIAL MEDIA",
    permissionKey: "cms",
    items: [
      { type: "link", label: "About Us", path: "/admin/food/pages-social-media/about", icon: "Globe", permissionKey: "cms" },
      { type: "link", label: "Terms & Conditions", path: "/admin/food/pages-social-media/terms", icon: "FileText", permissionKey: "cms" },
      { type: "link", label: "Support", path: "/admin/food/pages-social-media/support", icon: "HelpCircle", permissionKey: "cms" },
      { type: "link", label: "Privacy Policy", path: "/admin/food/pages-social-media/privacy", icon: "Lock", permissionKey: "cms" },
      { type: "link", label: "Refund Policy", path: "/admin/food/pages-social-media/refund", icon: "Receipt", permissionKey: "cms" },
      { type: "link", label: "Shipping Policy", path: "/admin/food/pages-social-media/shipping", icon: "Truck", permissionKey: "cms" },
      { type: "link", label: "Cancellation Policy", path: "/admin/food/pages-social-media/cancellation", icon: "X", permissionKey: "cms" },
    ],
  },
];
