export const quickAdminSidebarMenu = [
  {
    type: "link",
    label: "Dashboard",
    path: "/admin/quick-commerce",
    icon: "LayoutDashboard",
    permissionKey: "dashboard",
  },
  {
    type: "section",
    label: "CORE MANAGEMENT",
    permissionKey: "restaurants",
    items: [
      {
        type: "link",
        label: "Seller Requests",
        path: "/admin/quick-commerce/seller-requests",
        icon: "ClipboardCheck",
        permissionKey: "restaurants",
      },
      {
        type: "expandable",
        label: "Categories",
        icon: "FolderTree",
        permissionKey: "categories",
        subItems: [
          { label: "All Categories", path: "/admin/quick-commerce/categories/hierarchy" },
          { label: "Header Categories", path: "/admin/quick-commerce/categories/header" },
          { label: "Main Categories", path: "/admin/quick-commerce/categories/level2" },
          { label: "Sub-Categories", path: "/admin/quick-commerce/categories/sub" },
        ],
      },
      { type: "link", label: "Products", path: "/admin/quick-commerce/products", icon: "Package", permissionKey: "foods" },
      { type: "link", label: "Zone Setup", path: "/admin/quick-commerce/zone-setup", icon: "MapPin", permissionKey: "zones" },
      {
        type: "expandable",
        label: "Marketing Tools",
        icon: "Megaphone",
        permissionKey: "promotions",
        subItems: [
          { label: "Content Manager", path: "/admin/quick-commerce/experience-studio" },
          { label: "Hero & Categories Per Page", path: "/admin/quick-commerce/hero-categories" },
          { label: "Send Notifications", path: "/admin/quick-commerce/notifications" },
          { label: "Coupons & Promos", path: "/admin/quick-commerce/coupons" },
          { label: "Offer Sections", path: "/admin/quick-commerce/offer-sections" },
          { label: "Shop by Store", path: "/admin/quick-commerce/shop-by-store" },
        ],
      },
      {
        type: "expandable",
        label: "Customer Support",
        icon: "MessageSquare",
        permissionKey: "support",
        subItems: [
          { label: "Help Tickets", path: "/admin/quick-commerce/support-tickets" },
          { label: "Review Content", path: "/admin/quick-commerce/moderation" },
        ],
      },
      {
        type: "expandable",
        label: "Sellers",
        icon: "Building2",
        permissionKey: "restaurants",
        subItems: [
          { label: "Active Sellers", path: "/admin/quick-commerce/sellers/active" },
          { label: "Waiting for Review", path: "/admin/quick-commerce/sellers/pending" },
          { label: "Seller Locations", path: "/admin/quick-commerce/seller-locations" },
          { label: "Seller Commission", path: "/admin/quick-commerce/sellers/commission" },
        ],
      },
      { type: "link", label: "Transaction Report", path: "/admin/quick-commerce/transactions", icon: "FileText", permissionKey: "reports" },
      { type: "link", label: "Money Requests", path: "/admin/quick-commerce/withdrawals", icon: "CreditCard", permissionKey: "wallet" },
      { type: "link", label: "Seller Payments", path: "/admin/quick-commerce/seller-transactions", icon: "Receipt", permissionKey: "wallet" },
      { type: "link", label: "Collect Cash", path: "/admin/quick-commerce/cash-collection", icon: "IndianRupee", permissionKey: "wallet" },
      {
        type: "expandable",
        label: "Returns",
        icon: "Package",
        permissionKey: "orders",
        subItems: [
          { label: "Return Requests", path: "/admin/quick-commerce/returns" },
          { label: "Return Settings", path: "/admin/quick-commerce/returns/settings" },
        ],
      },
      {
        type: "expandable",
        label: "Orders",
        icon: "FileText",
        permissionKey: "orders",
        subItems: [
          { label: "All Orders", path: "/admin/quick-commerce/orders/all" },
          { label: "New Orders", path: "/admin/quick-commerce/orders/pending" },
          { label: "On the Way", path: "/admin/quick-commerce/orders/out-for-delivery" },
          { label: "Delivered", path: "/admin/quick-commerce/orders/delivered" },
          { label: "Cancelled", path: "/admin/quick-commerce/orders/cancelled" },
          { label: "Returned", path: "/admin/quick-commerce/orders/returned" },
        ],
      },
      { type: "link", label: "Fees & Charges", path: "/admin/quick-commerce/billing", icon: "DollarSign", permissionKey: "fee_settings" },
      { type: "link", label: "My Profile", path: "/admin/quick-commerce/profile", icon: "User", permissionKey: "settings" },
    ],
  },
];
